**Creating numpy array from 1-D List**

In [2]:
import numpy

In [3]:
lst=[87,44,12,34,23,76,89,54,22,21,53,39]
print(type(lst))
print(lst)

arr=numpy.array(lst)
print(type(arr))
print(arr)

<class 'list'>
[87, 44, 12, 34, 23, 76, 89, 54, 22, 21, 53, 39]
<class 'numpy.ndarray'>
[87 44 12 34 23 76 89 54 22 21 53 39]


**Creating numpy array from 2-D List**

In [5]:
lst=[
    [12,23,34,45],
    [67,78,89,90],
    [87,65,54,32]
]
print(lst)

arr=numpy.array(lst)
print(arr)

[[12, 23, 34, 45], [67, 78, 89, 90], [87, 65, 54, 32]]
[[12 23 34 45]
 [67 78 89 90]
 [87 65 54 32]]


In [6]:
res=arr+5
print(res)

[[17 28 39 50]
 [72 83 94 95]
 [92 70 59 37]]


In [7]:
res=arr**2
print(res)

[[ 144  529 1156 2025]
 [4489 6084 7921 8100]
 [7569 4225 2916 1024]]


**Creating numpy array with 0s, 1s and some value**

In [8]:
zarr=numpy.zeros((4,5))
print(zarr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
oarr=numpy.ones(7)
print(oarr)

[1. 1. 1. 1. 1. 1. 1.]


In [12]:
narr=numpy.full((2,5),9)
print(narr)

[[9 9 9 9 9]
 [9 9 9 9 9]]


**Creating identity matrix**

In [13]:
iarr=numpy.eye(5)
print(iarr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**Creating numpy array using arange()**

In [14]:
arr=numpy.arange(1,25)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [15]:
arr=numpy.arange(75,90,2)
print(arr)

[75 77 79 81 83 85 87 89]


In [16]:
arr=numpy.arange(50,25,-3)
print(arr)

[50 47 44 41 38 35 32 29 26]


**Creating array with linear spacing**

In [17]:
arr=numpy.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [18]:
arr=numpy.linspace(1,13,9)
print(arr)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]
