**More ways of creating NumPy arrays**

In [1]:
import numpy

In [2]:
farr=numpy.fromfunction(lambda i,j:i+j, (3,3),dtype=int)
print(farr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [8]:
f=lambda i,j:i+j
print(f(1,2))

3


In [9]:
arr=numpy.random.random(10)
print(arr)

[0.35818248 0.69743924 0.59631956 0.82329078 0.61686882 0.4070616
 0.26481384 0.20292886 0.77310054 0.96708876]


In [10]:
arr=numpy.random.random((3,5))
print(arr)

[[0.76806136 0.5055484  0.35940262 0.99870999 0.79772053]
 [0.57669324 0.20315453 0.60286618 0.99954318 0.78247642]
 [0.91231026 0.44786763 0.5773962  0.42357068 0.89143521]]


In [19]:
arr=numpy.random.randint(10)
print(arr)

6


In [20]:
arr=numpy.random.randint(1,50,10)
print(arr)

[38 43 48  3 34  8 12 46  9 19]


In [22]:
x=numpy.random.choice(arr)
print(x)

46


In [24]:
arr=numpy.random.randint(1,50,(3,4))
print(arr)

[[33 47 45  6]
 [ 1 12  3 18]
 [49 11 47 41]]
