**Mathematical operations on NumPy data**

In [2]:
import numpy

Basic arithmetic ops

In [ ]:
arr1=numpy.array([1,2,3,4])
arr2=numpy.array([8,6,9,8])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[ 9  8 12 12]
[-7 -4 -6 -4]
[ 8 12 27 32]
[0.125      0.33333333 0.33333333 0.5       ]


scalar ops

In [ ]:
arr1=numpy.array([1,2,3,4,5,6,7])
print(arr1+3)
print(arr1*2)
print(arr1**2)

[ 4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14]
[ 1  4  9 16 25 36 49]


aggregate functions

In [6]:
arr=numpy.array([1,2,3,4,5,6,7,8,9])

print(arr.sum())
print(arr.mean())
print(arr.std())
print('Correlation coefficient',numpy.corrcoef(arr))
print('varience',numpy.var(arr))
print(arr.min())
print(arr.max())
print(arr.prod())

45
5.0
2.581988897471611
Correlation coefficient 1.0
varience 6.666666666666667
1
9
362880


matrix operations

In [ ]:
a=numpy.array([[9,2],[3,4]])
b=numpy.array([[5,6],[7,8]])

print(numpy.dot(a,b))

[[59 70]
 [43 50]]


Element-wise math functions

In [ ]:
a=numpy.array([1,2,3,4,5])
print(numpy.sin(a))
print(numpy.cos(a))
print(numpy.tan(a))
print(numpy.log(a))
print(numpy.sqrt(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.41421356 1.73205081 2.         2.23606798]


rounding and absolute

In [ ]:
arr=numpy.array([1.4,2.6,-3.7])
print(numpy.round(arr))
print(numpy.ceil(arr))
print(numpy.abs(arr))


[ 1.  3. -4.]
[ 2.  3. -3.]
[1.4 2.6 3.7]


comparisons

In [ ]:
a=numpy.array([1,2,3])
b=numpy.array([4,2,5])
print(a==b)
print(a>b)

[False  True False]
[False False False]


In [7]:
a1=numpy.array([[12,23],[45,34],[65,49]])
a2=numpy.array([[11,59],[45,73],[71,49]])
comp=(a1==a2)
print(comp)


[[False False]
 [ True False]
 [False  True]]


In [8]:
print(comp.all())

False


In [9]:
if comp.all():
  print('numpy arrays are same')
else:
  print('numpy arrays are different')

numpy arrays are different


Broadcasting

In [10]:
a=numpy.array([[1,2,3],[4,5,6]])
b=numpy.array([1,0,-1])
#add b to each row of a
print(a+b)

[[2 2 2]
 [5 5 5]]


cumulative ops

In [12]:
a=numpy.array([1,2,3,4,5])
print(numpy.cumsum(a))
print(numpy.cumprod(a))

[ 1  3  6 10 15]
[  1   2   6  24 120]


clip & where

In [16]:
arr=numpy.array([10,20,30,40,50])
print(numpy.clip(arr,15,45))
print(numpy.where(arr>20,'yes','no'))

[15 20 30 40 45]
['no' 'no' 'yes' 'yes' 'yes']
