Join data of two numpy arrays

In [1]:
import numpy

In [2]:
a1=numpy.array([1,2,3,4,5])
a2=numpy.array([10,20,30,40,50,60,70])


In [3]:
res=numpy.concatenate((a1,a2))
print(res)

[ 1  2  3  4  5 10 20 30 40 50 60 70]


In [5]:
a1=numpy.array([[1,2,3],[4,5,6]])
a2=numpy.array([[12,23,34],[45,56,67],[20,50,10]])
res=numpy.concatenate((a1,a2))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [12 23 34]
 [45 56 67]
 [20 50 10]]


In [7]:
a1=numpy.array([[1,2,3],[4,5,6]])
a2=numpy.array([[12,23],[45,56]])
res=numpy.concatenate((a1,a2),axis=1)
print(res)

[[ 1  2  3 12 23]
 [ 4  5  6 45 56]]
