In [1]:
import numpy

In [2]:
a1=numpy.array([12,23,34,45,56,67,20,50,10])
print(a1)

[12 23 34 45 56 67 20 50 10]


In [ ]:
print(a1[0])

12


In [ ]:
print(a1[5])

67


In [ ]:
print(a1[2:6])

[34 45 56 67]


In [ ]:
print(a1[-1])

10


In [5]:
print(a1[4:])

[56 67 20 50 10]


In [6]:
print(a1[:])

[12 23 34 45 56 67 20 50 10]


In [7]:
print(a1[:5])

[12 23 34 45 56]


In [12]:
a2=numpy.array([[12,23,34,11,22],[45,56,67,33,44],[20,50,10,55,66]])
print(a2)

[[12 23 34 11 22]
 [45 56 67 33 44]
 [20 50 10 55 66]]


In [13]:
print(a2[1,2])

67


In [14]:
print(a2[:,:])

[[12 23 34 11 22]
 [45 56 67 33 44]
 [20 50 10 55 66]]


In [15]:
print(a2[1:,:])

[[45 56 67 33 44]
 [20 50 10 55 66]]


In [17]:
print(a2[1:,1:4])

[[56 67 33]
 [50 10 55]]
