In [1]:
import numpy

In [3]:
a1=numpy.array([12,23,34,45,56,67,20,50,10])
print(a1)

[12 23 34 45 56 67 20 50 10]


In [4]:
print(a1[0])

12


In [5]:
print(a1[5])

67


In [6]:
print(a1[2:6])

[34 45 56 67]


In [7]:
print(a1[-1])

10


In [10]:
a2=numpy.array([[12,23,34],[45,56,67],[20,50,10]])
print(a2)

[[12 23 34]
 [45 56 67]
 [20 50 10]]


In [9]:
print(a2[1,2])

67


In [11]:
print(a2[:,:])

[[12 23 34]
 [45 56 67]
 [20 50 10]]
