In [1]:
import numpy

In [2]:
arr=numpy.random.randint(1,75,10)
print(arr)

[38 14  6 73  7  8 21 61 15 42]


**Filter data**

In [3]:
filtered_arr=arr[arr>50]
print(filtered_arr)

[73 61]


**Sorting data**

In [7]:
print(arr)
print(arr[::-1])

print(numpy.sort(arr))
print(numpy.sort(arr)[::-1])

[38 14  6 73  7  8 21 61 15 42]
[42 15 61 21  8  7 73  6 14 38]
[ 6  7  8 14 15 21 38 42 61 73]
[73 61 42 38 21 15 14  8  7  6]


**Unique elements**

In [9]:
lst=[9,26,13,1,9,12,45,13,9,26,1,39]
a=numpy.array(lst)
print(a)

print(numpy.unique(a))

[ 9 26 13  1  9 12 45 13  9 26  1 39]
[ 1  9 12 13 26 39 45]


**Split**

In [13]:
print(a)
print(numpy.array_split(a,5))
print(numpy.array_split(a,5)[1])

[ 9 26 13  1  9 12 45 13  9 26  1 39]
[array([ 9, 26, 13]), array([ 1,  9, 12]), array([45, 13]), array([ 9, 26]), array([ 1, 39])]
[ 1  9 12]


In [18]:
print(a)
print(a.shape)
#ndarr=a.reshape(5,3)
#ValueError: cannot reshape array of size 12 into shape (5,3)
ndarr=a.reshape(3,4)
print(ndarr)

[ 9 26 13  1  9 12 45 13  9 26  1 39]
(12,)
[[ 9 26 13  1]
 [ 9 12 45 13]
 [ 9 26  1 39]]


In [19]:
lst=a.tolist()
print(a)
print(lst)

[ 9 26 13  1  9 12 45 13  9 26  1 39]
[9, 26, 13, 1, 9, 12, 45, 13, 9, 26, 1, 39]
